import os
import subprocess
import logging
import tempfile
import re
from flask import Flask, request, send_file, jsonify

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")

app = Flask(__name__)
app.config['MAX_CONTENT_LENGTH'] = 500 * 1024 * 1024  # Maks 500MB upload

def safe_remove(file_path):
    try:
        if os.path.exists(file_path):
            os.remove(file_path)
    except Exception as e:
        logging.warning(f"Gagal menghapus {file_path}: {e}")

@app.route("/", methods=["GET"])
def home():
    return "FFmpeg API is running!"

@app.route("/process-video", methods=["POST"])
def process_video():
    if "file" not in request.files:
        return jsonify({"error": "No file uploaded!"}), 400

    file = request.files["file"]

    with tempfile.NamedTemporaryFile(delete=False, suffix=".mp4") as temp_input:
        input_path = temp_input.name
        file.save(input_path)

    with tempfile.NamedTemporaryFile(delete=False, suffix=".mp4") as temp_output:
        output_path = temp_output.name

    logging.info(f"Processing video: {input_path}")

    ffmpeg_path = subprocess.run(["which", "ffmpeg"], capture_output=True, text=True).stdout.strip()
    if not ffmpeg_path:
        ffmpeg_path = "ffmpeg"

    # 🔍 Dapatkan durasi video
    duration_cmd = [ffmpeg_path, "-i", input_path]
    duration_result = subprocess.run(duration_cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)

    match = re.search(r"Duration: (\d+):(\d+):(\d+\.\d+)", duration_result.stderr)
    if match:
        hours, minutes, seconds = map(float, match.groups())
        duration = hours * 3600 + minutes * 60 + seconds - 1  
    else:
        logging.error("Gagal mendapatkan durasi video!")
        safe_remove(input_path)
        return jsonify({"error": "Failed to get video duration!"}), 500

    # ⚙️ Perintah FFmpeg dengan proteksi dari deteksi reupload
    command = [
        ffmpeg_path, "-y",
        "-loglevel", "info",
        "-hide_banner",
        "-fflags", "+genpts",
        "-r", "30",
        "-vsync", "vfr",
        "-i", input_path,
        "-t", str(duration - 1),
        
        # 🎨 Filter visual (lebih kuat)
        "-vf", "eq=contrast=1.03:brightness=0.02:saturation=1.05,"  # Sedikit tweak warna
               "noise=alls=5:allf=t+u,"  # Noise lebih variatif
               "gblur=sigma=0.5+random(0.2),"  # Blur berubah-ubah
               "tblend=all_mode=lighten:all_opacity=0.07,"  # Blur acak
               "drawtext=text=' ':fontsize=30:fontcolor=white@0.02:"
               "x=rand(10\,w-60):y=rand(10\,h-60)",  # Watermark sangat halus & random

        # 🎥 Encoding video
        "-c:v", "libx264",
        "-profile:v", "high",  
        "-preset", "ultrafast",
        "-crf", "30",  # Turunkan kualitas sedikit agar lebih unik
        "-b:v", "1200k",
        "-pix_fmt", "yuv420p",
        "-filter:v", "setpts=PTS*1.002",  # Perubahan speed sangat kecil

        # 🔊 Audio processing (lebih variatif)
        "-c:a", "aac",
        "-b:a", "128k",
        "-af", "rubberband=pitch=1.01+random(0.005),volume=1.03",  # Pitch shift acak

        # 🔄 Sinkronisasi & metadata unik
        "-strict", "-2",
        "-shortest",
        "-movflags", "+faststart",
        "-map_metadata", "-1",  # Hapus metadata asli
        "-metadata", f"title=Processed Video {os.urandom(4).hex()}",
        "-metadata", "encoder=Custom AI",
        "-metadata", "comment=Generated by Anti-Reupload System",
        
        output_path
    ]

    try:
        result = subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, timeout=600)
    except subprocess.TimeoutExpired:
        logging.error("FFmpeg timeout! Video terlalu lama diproses.")
        safe_remove(input_path)
        safe_remove(output_path)
        return jsonify({"error": "Processing timeout!"}), 500

    logging.info(f"FFmpeg Exit Code: {result.returncode}")
    logging.debug(f"FFmpeg Output: {result.stdout}")
    logging.error(f"FFmpeg Error: {result.stderr}" if result.returncode != 0 else "FFmpeg berhasil!")

    if result.returncode != 0 or not os.path.exists(output_path) or os.stat(output_path).st_size == 0:
        logging.error("FFmpeg gagal atau output video kosong!")
        safe_remove(input_path)
        safe_remove(output_path)
        return jsonify({"error": "FFmpeg failed or output file is empty!"}), 500

    response = send_file(output_path, as_attachment=True)

    safe_remove(input_path)
    safe_remove(output_path)

    return response

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 8080))
    app.run(host="0.0.0.0", port=port, debug=True)
